# Extracted from http://www.minecraft-servers-list.org/ide-list/
#
def block_by_id(id, data=0):
    b = [x for x in block_library if x["id"] == id and x["data"] == data]
    if len(b) == 0:
        b = [x for x in block_library if x["id"] == id]

    return b or [{"name":"Unknown", "id":0, "data":0}]

def name_by_id(id, data=0):
    b = [x for x in block_library if x["id"] == id and x["data"] == data]
    if len(b) == 0:
        b = [x for x in block_library if x["id"] == id]

    out = "Unknown"
    if (b and len(b)>0 and b[0] and b[0]["name"]):
        out = b[0]["name"]
    return out

def match(name):
    b = [x for x in block_library if x["name"].lower() == name.lower()]
    return b or block_library[0]


block_library = [{"name":"Air", "id":0, "data":0, "type":"Block"},
{"name":"Stone", "id":1, "data":0, "type":"Block"},
{"name":"Granite", "id":1, "data": 1, "type":"Block"},
{"name":"Polished Granite", "id":1, "data": 2, "type":"Block"},
{"name":"Diorite", "id":1, "data": 3, "type":"Block"},
{"name":"Polished Diorite", "id":1, "data": 4, "type":"Block"},
{"name":"Andesite", "id":1, "data": 5, "type":"Block"},
{"name":"Polished Andesite", "id":1, "data": 6, "type":"Block"},
{"name":"Grass", "id":2, "data":0, "type":"Block"},
{"name":"Dirt", "id":3, "data":0, "type":"Block"},
{"name":"Coarse Dirt", "id":3, "data": 1, "type":"Block"},
{"name":"Podzol", "id":3, "data": 2, "type":"Block"},
{"name":"Cobblestone", "id":4, "data":0, "type":"Block"},
{"name":"Oak Wood Plank", "id":5, "data":0, "type":"Block"},
{"name":"Spruce Wood Plank", "id":5, "data": 1, "type":"Block"},
{"name":"Birch Wood Plank", "id":5, "data": 2, "type":"Block"},
{"name":"Jungle Wood Plank", "id":5, "data": 3, "type":"Block"},
{"name":"Acacia Wood Plank", "id":5, "data": 4, "type":"Block"},
{"name":"Dark Oak Wood Plank", "id":5, "data": 5, "type":"Block"},
{"name":"Oak Sapling", "id":6, "data":0, "type":"Block"},
{"name":"Spruce Sapling", "id":6, "data": 1, "type":"Block"},
{"name":"Birch Sapling", "id":6, "data": 2, "type":"Block"},
{"name":"Jungle Sapling", "id":6, "data": 3, "type":"Block"},
{"name":"Acacia Sapling", "id":6, "data": 4, "type":"Block"},
{"name":"Dark Oak Sapling", "id":6, "data": 5, "type":"Block"},
{"name":"Bedrock", "id":7, "data":0, "type":"Block"},
{"name":"Flowing Water", "id":8, "data":0, "type":"Block"},
{"name":"Still Water", "id":9, "data":0, "type":"Block"},
{"name":"Flowing Lava", "id":10, "data":0, "type":"Block"},
{"name":"Still Lava", "id":11, "data":0, "type":"Block"},
{"name":"Sand", "id":12, "data":0, "type":"Block"},
{"name":"Red Sand", "id":12, "data": 1, "type":"Block"},
{"name":"Gravel", "id":13, "data":0, "type":"Block"},
{"name":"Gold Ore", "id":14, "data":0, "type":"Block"},
{"name":"Iron Ore", "id":15, "data":0, "type":"Block"},
{"name":"Coal Ore", "id":16, "data":0, "type":"Block"},
{"name":"Oak Wood", "id":17, "data":0, "type":"Block"},
{"name":"Spruce Wood", "id":17, "data": 1, "type":"Block"},
{"name":"Birch Wood", "id":17, "data": 2, "type":"Block"},
{"name":"Jungle Wood", "id":17, "data": 3, "type":"Block"},
{"name":"Oak Leaves", "id":18, "data":0, "type":"Block"},
{"name":"Spruce Leaves", "id":18, "data": 1, "type":"Block"},
{"name":"Birch Leaves", "id":18, "data": 2, "type":"Block"},
{"name":"Jungle Leaves", "id":18, "data": 3, "type":"Block"},
{"name":"Sponge", "id":19, "data":0, "type":"Block"},
{"name":"Wet Sponge", "id":19, "data": 1, "type":"Block"},
{"name":"Glass", "id":20, "data":0, "type":"Block"},
{"name":"Lapis Lazuli Ore", "id":21, "data":0, "type":"Block"},
{"name":"Lapis Lazuli Block", "id":22, "data":0, "type":"Block"},
{"name":"Dispenser", "id":23, "data":0, "type":"Block"},
{"name":"Sandstone", "id":24, "data":0, "type":"Block"},
{"name":"Chiseled Sandstone", "id":24, "data": 1, "type":"Block"},
{"name":"Smooth Sandstone", "id":24, "data": 2, "type":"Block"},
{"name":"Note Block", "id":25, "data":0, "type":"Block"},
{"name":"Bed", "id":26, "data":0, "type":"Block", "double":True},
{"name":"Powered Rail", "id":27, "data":0, "type":"Block"},
{"name":"Detector Rail", "id":28, "data":0, "type":"Block"},
{"name":"Sticky Piston", "id":29, "data":0, "type":"Block"},
{"name":"Cobweb", "id":30, "data":0, "type":"Block"},
{"name":"Dead Shrub", "id":31, "data":0, "type":"Block"},
{"name":"Grass", "id":31, "data": 1, "type":"Block"},
{"name":"Fern", "id":31, "data": 2, "type":"Block"},
{"name":"Dead Shrub", "id":32, "data":0, "type":"Block"},
{"name":"Piston", "id":33, "data":0, "type":"Block"},
{"name":"Piston Head", "id":34, "data":0, "type":"Block"},
{"name":"White Wool", "id":35, "data":0, "type":"Block"},
{"name":"Orange Wool", "id":35, "data": 1, "type":"Block"},
{"name":"Magenta Wool", "id":35, "data": 2, "type":"Block"},
{"name":"Light Blue Wool", "id":35, "data": 3, "type":"Block"},
{"name":"Yellow Wool", "id":35, "data": 4, "type":"Block"},
{"name":"Lime Wool", "id":35, "data": 5, "type":"Block"},
{"name":"Pink Wool", "id":35, "data": 6, "type":"Block"},
{"name":"Gray Wool", "id":35, "data": 7, "type":"Block"},
{"name":"Light Gray Wool", "id":35, "data": 8, "type":"Block"},
{"name":"Cyan Wool", "id":35, "data": 9, "type":"Block"},
{"name":"Purple Wool", "id":35, "data": 10, "type":"Block"},
{"name":"Blue Wool", "id":35, "data": 11, "type":"Block"},
{"name":"Brown Wool", "id":35, "data": 12, "type":"Block"},
{"name":"Green Wool", "id":35, "data": 13, "type":"Block"},
{"name":"Red Wool", "id":35, "data": 14, "type":"Block"},
{"name":"Black Wool", "id":35, "data": 15, "type":"Block"},
{"name":"Dandelion", "id":37, "data":0},
{"name":"Poppy", "id":38, "data":0},
{"name":"Blue Orchid", "id":38, "data": 1},
{"name":"Allium", "id":38, "data": 2},
{"name":"Azure Bluet", "id":38, "data": 3},
{"name":"Red Tulip", "id":38, "data": 4},
{"name":"Orange Tulip", "id":38, "data": 5},
{"name":"White Tulip", "id":38, "data": 6},
{"name":"Pink Tulip", "id":38, "data": 7},
{"name":"Oxeye Daisy", "id":38, "data": 8},
{"name":"Brown Mushroom", "id":39, "data":0},
{"name":"Red Mushroom", "id":40, "data":0},
{"name":"Gold Block", "id":41, "data":0, "type":"Block"},
{"name":"Iron Block", "id":42, "data":0, "type":"Block"},
{"name":"Double Stone Slab", "id":43, "data":0, "type":"Block"},
{"name":"Double Sandstone Slab", "id":43, "data": 1, "type":"Block"},
{"name":"Double Wooden Slab", "id":43, "data": 2, "type":"Block"},
{"name":"Double Cobblestone Slab", "id":43, "data": 3, "type":"Block"},
{"name":"Double Brick Slab", "id":43, "data": 4, "type":"Block"},
{"name":"Double Stone Brick Slab", "id":43, "data": 5, "type":"Block"},
{"name":"Double Nether Brick Slab", "id":43, "data": 6, "type":"Block"},
{"name":"Double Quartz Slab", "id":43, "data": 7, "type":"Block"},
{"name":"Stone Slab", "id":44, "data":0, "type":"Block"},
{"name":"Sandstone Slab", "id":44, "data": 1, "type":"Block"},
{"name":"Wooden Slab", "id":44, "data": 2, "type":"Block"},
{"name":"Cobblestone Slab", "id":44, "data": 3, "type":"Block"},
{"name":"Brick Slab", "id":44, "data": 4, "type":"Block"},
{"name":"Stone Brick Slab", "id":44, "data": 5, "type":"Block"},
{"name":"Nether Brick Slab", "id":44, "data": 6, "type":"Block"},
{"name":"Quartz Slab", "id":44, "data": 7, "type":"Block"},
{"name":"Bricks", "id":45, "data":0, "type":"Block"},
{"name":"TNT", "id":46, "data":0, "type":"Block"},
{"name":"Bookshelf", "id":47, "data":0, "type":"Block"},
{"name":"Moss Stone", "id":48, "data":0, "type":"Block"},
{"name":"Obsidian", "id":49, "data":0, "type":"Block"},
{"name":"Torch", "id":50, "data":0},
{"name":"Fire", "id":51, "data":0},
{"name":"Monster Spawner", "id":52, "data":0},
{"name":"Oak Wood Stairs", "id":53, "data":0, "type":"Block"},
{"name":"Chest", "id":54, "data":0, "type":"Block", "interactive":True},
{"name":"Redstone Wire", "id":55, "data":0, "type":"Block", "interactive":True},
{"name":"Diamond Ore", "id":56, "data":0, "type":"Block"},
{"name":"Diamond Block", "id":57, "data":0, "type":"Block"},
{"name":"Crafting Table", "id":58, "data":0, "type":"Block", "interactive":True},
{"name":"Wheat Crops", "id":59, "data":0},
{"name":"Farmland", "id":60, "data":0, "type":"Block"},
{"name":"Furnace", "id":61, "data":0, "type":"Block", "interactive":True},
{"name":"Burning Furnace", "id":62, "data":0, "type":"Block", "interactive":True},
{"name":"Standing Sign Block", "id":63, "data":0},
{"name":"Oak Door Block", "id":64, "data":0, "type":"Block", "double":True},
{"name":"Ladder", "id":65, "data":0, "type":"Block", "interactive":True},
{"name":"Rail", "id":66, "data":0, "type":"Block", "interactive":True},
{"name":"Cobblestone Stairs", "id":67, "data":0, "type":"Block"},
{"name":"Wall-mounted Sign Block", "id":68, "data":0},
{"name":"Lever", "id":69, "data":0},
{"name":"Stone Pressure Plate", "id":70, "data":0},
{"name":"Iron Door Block", "id":71, "data":0, "type":"Block", "double":True},
{"name":"Wooden Pressure Plate", "id":72, "data":0},
{"name":"Redstone Ore", "id":73, "data":0, "type":"Block"},
{"name":"Glowing Redstone Ore", "id":74, "data":0, "type":"Block"},
{"name":"Redstone Torch (off)", "id":75, "data":0},
{"name":"Redstone Torch (on)", "id":76, "data":0},
{"name":"Stone Button", "id":77, "data":0},
{"name":"Snow", "id":78, "data":0, "type":"Block"},
{"name":"Ice", "id":79, "data":0, "type":"Block"},
{"name":"Snow Block", "id":80, "data":0, "type":"Block"},
{"name":"Cactus", "id":81, "data":0, "type":"Block"},
{"name":"Clay", "id":82, "data":0, "type":"Block"},
{"name":"Sugar Canes", "id":83, "data":0},
{"name":"Jukebox", "id":84, "data":0},
{"name":"Oak Fence", "id":85, "data":0, "type":"Block"},
{"name":"Pumpkin", "id":86, "data":0},
{"name":"Netherrack", "id":87, "data":0, "type":"Block"},
{"name":"Soul Sand", "id":88, "data":0, "type":"Block"},
{"name":"Glowstone", "id":89, "data":0, "type":"Block"},
{"name":"Nether Portal", "id":90, "data":0, "type":"Block"},
{"name":"Jack o'Lantern", "id":91, "data":0},
{"name":"Cake Block", "id":92, "data":0},
{"name":"Redstone Repeater Block (off)", "id":93, "data":0},
{"name":"Redstone Repeater Block (on)", "id":94, "data":0},
{"name":"White Stained Glass", "id":95, "data":0, "type":"Block"},
{"name":"Orange Stained Glass", "id":95, "data": 1, "type":"Block"},
{"name":"Magenta Stained Glass", "id":95, "data": 2, "type":"Block"},
{"name":"Light Blue Stained Glass", "id":95, "data": 3, "type":"Block"},
{"name":"Yellow Stained Glass", "id":95, "data": 4, "type":"Block"},
{"name":"Lime Stained Glass", "id":95, "data": 5, "type":"Block"},
{"name":"Pink Stained Glass", "id":95, "data": 6, "type":"Block"},
{"name":"Gray Stained Glass", "id":95, "data": 7, "type":"Block"},
{"name":"Light Gray Stained Glass", "id":95, "data": 8, "type":"Block"},
{"name":"Cyan Stained Glass", "id":95, "data": 9, "type":"Block"},
{"name":"Purple Stained Glass", "id":95, "data": 10, "type":"Block"},
{"name":"Blue Stained Glass", "id":95, "data": 11, "type":"Block"},
{"name":"Brown Stained Glass", "id":95, "data": 12, "type":"Block"},
{"name":"Green Stained Glass", "id":95, "data": 13, "type":"Block"},
{"name":"Red Stained Glass", "id":95, "data": 14, "type":"Block"},
{"name":"Black Stained Glass", "id":95, "data": 15, "type":"Block"},
{"name":"Wooden Trapdoor", "id":96, "data":0},
{"name":"Stone Monster Egg", "id":97, "data":0},
{"name":"Cobblestone Monster Egg", "id":97, "data": 1},
{"name":"Stone Brick Monster Egg", "id":97, "data": 2},
{"name":"Mossy Stone Brick Monster Egg", "id":97, "data": 3},
{"name":"Cracked Stone Brick Monster Egg", "id":97, "data": 4},
{"name":"Chiseled Stone Brick Monster Egg", "id":97, "data": 5},
{"name":"Stone Bricks", "id":98, "data":0, "type":"Block"},
{"name":"Mossy Stone Bricks", "id":98, "data": 1, "type":"Block"},
{"name":"Cracked Stone Bricks", "id":98, "data": 2, "type":"Block"},
{"name":"Chiseled Stone Bricks", "id":98, "data": 3, "type":"Block"},
{"name":"Red Mushroom Cap", "id":99, "data":0},
{"name":"Brown Mushroom Cap", "id":100, "data":0},
{"name":"Iron Bars", "id":101, "data":0},
{"name":"Glass Pane", "id":102, "data":0},
{"name":"Melon Block", "id":103, "data":0},
{"name":"Pumpkin Stem", "id":104, "data":0},
{"name":"Melon Stem", "id":105, "data":0},
{"name":"Vines", "id":106, "data":0},
{"name":"Oak Fence Gate", "id":107, "data":0},
{"name":"Brick Stairs", "id":108, "data":0, "type":"Block"},
{"name":"Stone Brick Stairs", "id":109, "data":0, "type":"Block"},
{"name":"Mycelium", "id":110, "data":0},
{"name":"Lily Pad", "id":111, "data":0},
{"name":"Nether Brick", "id":112, "data":0, "type":"Block"},
{"name":"Nether Brick Fence", "id":113, "data":0, "type":"Block"},
{"name":"Nether Brick Stairs", "id":114, "data":0, "type":"Block"},
{"name":"Nether Wart", "id":115, "data":0},
{"name":"Enchantment Table", "id":116, "data":0, "type":"Block"},
{"name":"Brewing Stand", "id":117, "data":0, "type":"Block"},
{"name":"Cauldron", "id":118, "data":0, "type":"Block"},
{"name":"End Portal", "id":119, "data":0},
{"name":"End Portal Frame", "id":120, "data":0},
{"name":"End Stone", "id":121, "data":0},
{"name":"Dragon Egg", "id":122, "data":0},
{"name":"Redstone Lamp (inactive)", "id":123, "data":0},
{"name":"Redstone Lamp (active)", "id":124, "data":0},
{"name":"Double Oak Wood Slab", "id":125, "data":0, "type":"Block"},
{"name":"Double Spruce Wood Slab", "id":125, "data": 1, "type":"Block"},
{"name":"Double Birch Wood Slab", "id":125, "data": 2, "type":"Block"},
{"name":"Double Jungle Wood Slab", "id":125, "data": 3, "type":"Block"},
{"name":"Double Acacia Wood Slab", "id":125, "data": 4, "type":"Block"},
{"name":"Double Dark Oak Wood Slab", "id":125, "data": 5, "type":"Block"},
{"name":"Oak Wood Slab", "id":126, "data":0, "type":"Block"},
{"name":"Spruce Wood Slab", "id":126, "data": 1, "type":"Block"},
{"name":"Birch Wood Slab", "id":126, "data": 2, "type":"Block"},
{"name":"Jungle Wood Slab", "id":126, "data": 3, "type":"Block"},
{"name":"Acacia Wood Slab", "id":126, "data": 4, "type":"Block"},
{"name":"Dark Oak Wood Slab", "id":126, "data": 5, "type":"Block"},
{"name":"Cocoa", "id":127, "data":0},
{"name":"Sandstone Stairs", "id":128, "data":0},
{"name":"Emerald Ore", "id":129, "data":0, "type":"Block"},
{"name":"Ender Chest", "id":130, "data":0},
{"name":"Tripwire Hook", "id":131, "data":0},
{"name":"Tripwire", "id":132, "data":0},
{"name":"Emerald Block", "id":133, "data":0, "type":"Block"},
{"name":"Spruce Wood Stairs", "id":134, "data":0, "type":"Block"},
{"name":"Birch Wood Stairs", "id":135, "data":0, "type":"Block"},
{"name":"Jungle Wood Stairs", "id":136, "data":0, "type":"Block"},
{"name":"Command Block", "id":137, "data":0, "type":"Block"},
{"name":"Beacon", "id":138, "data":0},
{"name":"Cobblestone Wall", "id":139, "data":0, "type":"Block"},
{"name":"Mossy Cobblestone Wall", "id":139, "data": 1, "type":"Block"},
{"name":"Flower Pot", "id":140, "data":0},
{"name":"Carrots", "id":141, "data":0},
{"name":"Potatoes", "id":142, "data":0},
{"name":"Wooden Button", "id":143, "data":0},
{"name":"Mob Head", "id":144, "data":0},
{"name":"Anvil", "id":145, "data":0},
{"name":"Trapped Chest", "id":146, "data":0},
{"name":"Weighted Pressure Plate (light)", "id":147, "data":0},
{"name":"Weighted Pressure Plate (heavy)", "id":148, "data":0},
{"name":"Redstone Comparator (inactive)", "id":149, "data":0},
{"name":"Redstone Comparator (active)", "id":150, "data":0},
{"name":"Daylight Sensor", "id":151, "data":0},
{"name":"Redstone Block", "id":152, "data":0},
{"name":"Nether Quartz Ore", "id":153, "data":0},
{"name":"Hopper", "id":154, "data":0},
{"name":"Quartz Block", "id":155, "data":0},
{"name":"Chiseled Quartz Block", "id":155, "data": 1},
{"name":"Pillar Quartz Block", "id":155, "data": 2},
{"name":"Quartz Stairs", "id":156, "data":0},
{"name":"Activator Rail", "id":157, "data":0},
{"name":"Dropper", "id":158, "data":0},
{"name":"White Stained Clay", "id":159, "data":0},
{"name":"Orange Stained Clay", "id":159, "data": 1},
{"name":"Magenta Stained Clay", "id":159, "data": 2},
{"name":"Light Blue Stained Clay", "id":159, "data": 3},
{"name":"Yellow Stained Clay", "id":159, "data": 4},
{"name":"Lime Stained Clay", "id":159, "data": 5},
{"name":"Pink Stained Clay", "id":159, "data": 6},
{"name":"Gray Stained Clay", "id":159, "data": 7},
{"name":"Light Gray Stained Clay", "id":159, "data": 8},
{"name":"Cyan Stained Clay", "id":159, "data": 9},
{"name":"Purple Stained Clay", "id":159, "data": 10},
{"name":"Blue Stained Clay", "id":159, "data": 11},
{"name":"Brown Stained Clay", "id":159, "data": 12},
{"name":"Green Stained Clay", "id":159, "data": 13},
{"name":"Red Stained Clay", "id":159, "data": 14},
{"name":"Black Stained Clay", "id":159, "data": 15},
{"name":"White Stained Glass Pane", "id":160, "data":0},
{"name":"Orange Stained Glass Pane", "id":160, "data": 1},
{"name":"Magenta Stained Glass Pane", "id":160, "data": 2},
{"name":"Light Blue Stained Glass Pane", "id":160, "data": 3},
{"name":"Yellow Stained Glass Pane", "id":160, "data": 4},
{"name":"Lime Stained Glass Pane", "id":160, "data": 5},
{"name":"Pink Stained Glass Pane", "id":160, "data": 6},
{"name":"Gray Stained Glass Pane", "id":160, "data": 7},
{"name":"Light Gray Stained Glass Pane", "id":160, "data": 8},
{"name":"Cyan Stained Glass Pane", "id":160, "data": 9},
{"name":"Purple Stained Glass Pane", "id":160, "data": 10},
{"name":"Blue Stained Glass Pane", "id":160, "data": 11},
{"name":"Brown Stained Glass Pane", "id":160, "data": 12},
{"name":"Green Stained Glass Pane", "id":160, "data": 13},
{"name":"Red Stained Glass Pane", "id":160, "data": 14},
{"name":"Black Stained Glass Pane", "id":160, "data": 15},
{"name":"Acacia Leaves", "id":161, "data":0},
{"name":"Dark Oak Leaves", "id":161, "data": 1},
{"name":"Acacia Wood", "id":162, "data":0},
{"name":"Dark Oak Wood", "id":162, "data": 1},
{"name":"Acacia Wood Stairs", "id":163, "data":0},
{"name":"Dark Oak Wood Stairs", "id":164, "data":0},
{"name":"Slime Block", "id":165, "data":0},
{"name":"Barrier", "id":166, "data":0},
{"name":"Iron Trapdoor", "id":167, "data":0},
{"name":"Prismarine", "id":168, "data":0},
{"name":"Prismarine Bricks", "id":168, "data": 1},
{"name":"Dark Prismarine", "id":168, "data": 2},
{"name":"Sea Lantern", "id":169, "data":0},
{"name":"Hay Bale", "id":170, "data":0},
{"name":"White Carpet", "id":171, "data":0},
{"name":"Orange Carpet", "id":171, "data": 1},
{"name":"Magenta Carpet", "id":171, "data": 2},
{"name":"Light Blue Carpet", "id":171, "data": 3},
{"name":"Yellow Carpet", "id":171, "data": 4},
{"name":"Lime Carpet", "id":171, "data": 5},
{"name":"Pink Carpet", "id":171, "data": 6},
{"name":"Gray Carpet", "id":171, "data": 7},
{"name":"Light Gray Carpet", "id":171, "data": 8},
{"name":"Cyan Carpet", "id":171, "data": 9},
{"name":"Purple Carpet", "id":171, "data": 10},
{"name":"Blue Carpet", "id":171, "data": 11},
{"name":"Brown Carpet", "id":171, "data": 12},
{"name":"Green Carpet", "id":171, "data": 13},
{"name":"Red Carpet", "id":171, "data": 14},
{"name":"Black Carpet", "id":171, "data": 15},
{"name":"Hardened Clay", "id":172, "data":0},
{"name":"Block of Coal", "id":173, "data":0},
{"name":"Packed Ice", "id":174, "data":0},
{"name":"Sunflower", "id":175, "data":0},
{"name":"Lilac", "id":175, "data": 1},
{"name":"Double Tallgrass", "id":175, "data": 2},
{"name":"Large Fern", "id":175, "data": 3},
{"name":"Rose Bush", "id":175, "data": 4},
{"name":"Peony", "id":175, "data": 5},
{"name":"Free-standing Banner", "id":176, "data":0},
{"name":"Wall-mounted Banner", "id":177, "data":0},
{"name":"Inverted Daylight Sensor", "id":178, "data":0},
{"name":"Red Sandstone", "id":179, "data":0},
{"name":"Smooth Red Sandstone", "id":179, "data": 1},
{"name":"Chiseled Red Sandstone", "id":179, "data": 2},
{"name":"Red Sandstone Stairs", "id":180, "data":0},
{"name":"Double Red Sandstone Slab", "id":181, "data":0},
{"name":"Red Sandstone Slab", "id":182, "data":0},
{"name":"Spruce Fence Gate", "id":183, "data":0},
{"name":"Birch Fence Gate", "id":184, "data":0},
{"name":"Jungle Fence Gate", "id":185, "data":0},
{"name":"Dark Oak Fence Gate", "id":186, "data":0},
{"name":"Acacia Fence Gate", "id":187, "data":0},
{"name":"Spruce Fence", "id":188, "data":0},
{"name":"Birch Fence", "id":189, "data":0},
{"name":"Jungle Fence", "id":190, "data":0},
{"name":"Dark Oak Fence", "id":191, "data":0},
{"name":"Acacia Fence", "id":192, "data":0},
{"name":"Spruce Door Block", "id":193, "data":0},
{"name":"Birch Door Block", "id":194, "data":0},
{"name":"Jungle Door Block", "id":195, "data":0},
{"name":"Acacia Door Block", "id":196, "data":0},
{"name":"Dark Oak Door Block", "id":197, "data":0},
{"name":"End Rod", "id":198, "data":0},
{"name":"Chorus Plant", "id":199, "data":0},
{"name":"Chorus Flower", "id":200, "data":0},
{"name":"Purpur Block", "id":201, "data":0},
{"name":"Purpur Pillar", "id":202, "data":0},
{"name":"Purpur Stairs", "id":203, "data":0},
{"name":"Purpur Double Slab", "id":204, "data":0},
{"name":"Purpur Slab", "id":205, "data":0},
{"name":"End Stone Bricks", "id":206, "data":0},
{"name":"Beetroot Seeds", "id":207, "data":0},
{"name":"Grass Path", "id":208, "data":0},
{"name":"End Gateway", "id":209, "data":0},
{"name":"Repeating Command Block", "id":210, "data":0},
{"name":"Chain Command Block", "id":211, "data":0},
{"name":"Frosted Ice", "id":212, "data":0},
{"name":"Magma Block", "id":213, "data":0},
{"name":"Nether Wart Block", "id":214, "data":0},
{"name":"Red Nether Brick", "id":215, "data":0},
{"name":"Bone Block", "id":216, "data":0},
{"name":"Structure Void", "id":217, "data":0},
{"name":"Observer", "id":218, "data":0},
{"name":"White Shulker Box", "id":219, "data":0},
{"name":"Orange Shulker Box", "id":220, "data":0},
{"name":"Magenta Shulker Box", "id":221, "data":0},
{"name":"Light Blue Shulker Box", "id":222, "data":0},
{"name":"Yellow Shulker Box", "id":223, "data":0},
{"name":"Lime Shulker Box", "id":224, "data":0},
{"name":"Pink Shulker Box", "id":225, "data":0},
{"name":"Gray Shulker Box", "id":226, "data":0},
{"name":"Light Gray Shulker Box", "id":227, "data":0},
{"name":"Cyan Shulker Box", "id":228, "data":0},
{"name":"Purple Shulker Box", "id":229, "data":0},
{"name":"Blue Shulker Box", "id":230, "data":0},
{"name":"Brown Shulker Box", "id":231, "data":0},
{"name":"Green Shulker Box", "id":232, "data":0},
{"name":"Red Shulker Box", "id":233, "data":0},
{"name":"Black Shulker Box", "id":234, "data":0},
{"name":"White Glazed Terracotta", "id":235, "data":0},
{"name":"Orange Glazed Terracotta", "id":236, "data":0},
{"name":"Magenta Glazed Terracotta", "id":237, "data":0},
{"name":"Light Blue Glazed Terracotta", "id":238, "data":0},
{"name":"Yellow Glazed Terracotta", "id":239, "data":0},
{"name":"Lime Glazed Terracotta", "id":240, "data":0},
{"name":"Pink Glazed Terracotta", "id":241, "data":0},
{"name":"Gray Glazed Terracotta", "id":242, "data":0},
{"name":"Light Gray Glazed Terracotta", "id":243, "data":0},
{"name":"Cyan Glazed Terracotta", "id":244, "data":0},
{"name":"Purple Glazed Terracotta", "id":245, "data":0},
{"name":"Blue Glazed Terracotta", "id":246, "data":0},
{"name":"Brown Glazed Terracotta", "id":247, "data":0},
{"name":"Green Glazed Terracotta", "id":248, "data":0},
{"name":"Red Glazed Terracotta", "id":249, "data":0},
{"name":"Black Glazed Terracotta", "id":250, "data":0},
{"name":"White Concrete", "id":251, "data":0},
{"name":"Orange Concrete", "id":251, "data": 1},
{"name":"Magenta Concrete", "id":251, "data": 2},
{"name":"Light Blue Concrete", "id":251, "data": 3},
{"name":"Yellow Concrete", "id":251, "data": 4},
{"name":"Lime Concrete", "id":251, "data": 5},
{"name":"Pink Concrete", "id":251, "data": 6},
{"name":"Gray Concrete", "id":251, "data": 7},
{"name":"Light Gray Concrete", "id":251, "data": 8},
{"name":"Cyan Concrete", "id":251, "data": 9},
{"name":"Purple Concrete", "id":251, "data": 10},
{"name":"Blue Concrete", "id":251, "data": 11},
{"name":"Brown Concrete", "id":251, "data": 12},
{"name":"Green Concrete", "id":251, "data": 13},
{"name":"Red Concrete", "id":251, "data": 14},
{"name":"Black Concrete", "id":251, "data": 15},
{"name":"White Concrete Powder", "id":252, "data":0},
{"name":"Orange Concrete Powder", "id":252, "data": 1},
{"name":"Magenta Concrete Powder", "id":252, "data": 2},
{"name":"Light Blue Concrete Powder", "id":252, "data": 3},
{"name":"Yellow Concrete Powder", "id":252, "data": 4},
{"name":"Lime Concrete Powder", "id":252, "data": 5},
{"name":"Pink Concrete Powder", "id":252, "data": 6},
{"name":"Gray Concrete Powder", "id":252, "data": 7},
{"name":"Light Gray Concrete Powder", "id":252, "data": 8},
{"name":"Cyan Concrete Powder", "id":252, "data": 9},
{"name":"Purple Concrete Powder", "id":252, "data": 10},
{"name":"Blue Concrete Powder", "id":252, "data": 11},
{"name":"Brown Concrete Powder", "id":252, "data": 12},
{"name":"Green Concrete Powder", "id":252, "data": 13},
{"name":"Red Concrete Powder", "id":252, "data": 14},
{"name":"Black Concrete Powder", "id":252, "data": 15},
{"name":"Structure Block", "id":255, "data":0},
{"name":"Iron Shovel", "id":256, "data":0},
{"name":"Iron Pickaxe", "id":257, "data":0},
{"name":"Iron Axe", "id":258, "data":0},
{"name":"Flint and Steel", "id":259, "data":0},
{"name":"Apple", "id":260, "data":0},
{"name":"Bow", "id":261, "data":0},
{"name":"Arrow", "id":262, "data":0},
{"name":"Coal", "id":263, "data":0},
{"name":"Charcoal", "id":263, "data": 1},
{"name":"Diamond", "id":264, "data":0},
{"name":"Iron Ingot", "id":265, "data":0},
{"name":"Gold Ingot", "id":266, "data":0},
{"name":"Iron Sword", "id":267, "data":0},
{"name":"Wooden Sword", "id":268, "data":0},
{"name":"Wooden Shovel", "id":269, "data":0},
{"name":"Wooden Pickaxe", "id":270, "data":0},
{"name":"Wooden Axe", "id":271, "data":0},
{"name":"Stone Sword", "id":272, "data":0},
{"name":"Stone Shovel", "id":273, "data":0},
{"name":"Stone Pickaxe", "id":274, "data":0},
{"name":"Stone Axe", "id":275, "data":0},
{"name":"Diamond Sword", "id":276, "data":0},
{"name":"Diamond Shovel", "id":277, "data":0},
{"name":"Diamond Pickaxe", "id":278, "data":0},
{"name":"Diamond Axe", "id":279, "data":0},
{"name":"Stick", "id":280, "data":0},
{"name":"Bowl", "id":281, "data":0},
{"name":"Mushroom Stew", "id":282, "data":0},
{"name":"Golden Sword", "id":283, "data":0},
{"name":"Golden Shovel", "id":284, "data":0},
{"name":"Golden Pickaxe", "id":285, "data":0},
{"name":"Golden Axe", "id":286, "data":0},
{"name":"String", "id":287, "data":0},
{"name":"Feather", "id":288, "data":0},
{"name":"Gunpowder", "id":289, "data":0},
{"name":"Wooden Hoe", "id":290, "data":0},
{"name":"Stone Hoe", "id":291, "data":0},
{"name":"Iron Hoe", "id":292, "data":0},
{"name":"Diamond Hoe", "id":293, "data":0},
{"name":"Golden Hoe", "id":294, "data":0},
{"name":"Wheat Seeds", "id":295, "data":0},
{"name":"Wheat", "id":296, "data":0},
{"name":"Bread", "id":297, "data":0},
{"name":"Leather Helmet", "id":298, "data":0},
{"name":"Leather Tunic", "id":299, "data":0},
{"name":"Leather Pants", "id":300, "data":0},
{"name":"Leather Boots", "id":301, "data":0},
{"name":"Chainmail Helmet", "id":302, "data":0},
{"name":"Chainmail Chestplate", "id":303, "data":0},
{"name":"Chainmail Leggings", "id":304, "data":0},
{"name":"Chainmail Boots", "id":305, "data":0},
{"name":"Iron Helmet", "id":306, "data":0},
{"name":"Iron Chestplate", "id":307, "data":0},
{"name":"Iron Leggings", "id":308, "data":0},
{"name":"Iron Boots", "id":309, "data":0},
{"name":"Diamond Helmet", "id":310, "data":0},
{"name":"Diamond Chestplate", "id":311, "data":0},
{"name":"Diamond Leggings", "id":312, "data":0},
{"name":"Diamond Boots", "id":313, "data":0},
{"name":"Golden Helmet", "id":314, "data":0},
{"name":"Golden Chestplate", "id":315, "data":0},
{"name":"Golden Leggings", "id":316, "data":0},
{"name":"Golden Boots", "id":317, "data":0},
{"name":"Flint", "id":318, "data":0},
{"name":"Raw Porkchop", "id":319, "data":0},
{"name":"Cooked Porkchop", "id":320, "data":0},
{"name":"Painting", "id":321, "data":0},
{"name":"Golden Apple", "id":322, "data":0},
{"name":"Enchanted Golden Apple", "id":322, "data": 1},
{"name":"Sign", "id":323, "data":0},
{"name":"Oak Door", "id":324, "data":0},
{"name":"Bucket", "id":325, "data":0},
{"name":"Water Bucket", "id":326, "data":0},
{"name":"Lava Bucket", "id":327, "data":0},
{"name":"Minecart", "id":328, "data":0},
{"name":"Saddle", "id":329, "data":0},
{"name":"Iron Door", "id":330, "data":0},
{"name":"Redstone", "id":331, "data":0},
{"name":"Snowball", "id":332, "data":0},
{"name":"Boat", "id":333, "data":0},
{"name":"Leather", "id":334, "data":0},
{"name":"Milk Bucket", "id":335, "data":0},
{"name":"Brick", "id":336, "data":0},
{"name":"Clay", "id":337, "data":0},
{"name":"Sugar Canes", "id":338, "data":0},
{"name":"Paper", "id":339, "data":0},
{"name":"Book", "id":340, "data":0},
{"name":"Slimeball", "id":341, "data":0},
{"name":"Minecart with Chest", "id":342, "data":0},
{"name":"Minecart with Furnace", "id":343, "data":0},
{"name":"Egg", "id":344, "data":0},
{"name":"Compass", "id":345, "data":0},
{"name":"Fishing Rod", "id":346, "data":0},
{"name":"Clock", "id":347, "data":0},
{"name":"Glowstone Dust", "id":348, "data":0},
{"name":"Raw Fish", "id":349, "data":0},
{"name":"Raw Salmon", "id":349, "data": 1},
{"name":"Clownfish", "id":349, "data": 2},
{"name":"Pufferfish", "id":349, "data": 3},
{"name":"Cooked Fish", "id":350, "data":0},
{"name":"Cooked Salmon", "id":350, "data": 1},
{"name":"Ink Sack", "id":351, "data":0},
{"name":"Rose Red", "id":351, "data": 1},
{"name":"Cactus Green", "id":351, "data": 2},
{"name":"Coco Beans", "id":351, "data": 3},
{"name":"Lapis Lazuli", "id":351, "data": 4},
{"name":"Purple Dye", "id":351, "data": 5},
{"name":"Cyan Dye", "id":351, "data": 6},
{"name":"Light Gray Dye", "id":351, "data": 7},
{"name":"Gray Dye", "id":351, "data": 8},
{"name":"Pink Dye", "id":351, "data": 9},
{"name":"Lime Dye", "id":351, "data": 10},
{"name":"Dandelion Yellow", "id":351, "data": 11},
{"name":"Light Blue Dye", "id":351, "data": 12},
{"name":"Magenta Dye", "id":351, "data": 13},
{"name":"Orange Dye", "id":351, "data": 14},
{"name":"Bone Meal", "id":351, "data": 15},
{"name":"Bone", "id":352, "data":0},
{"name":"Sugar", "id":353, "data":0},
{"name":"Cake", "id":354, "data":0},
{"name":"Bed", "id":355, "data":0},
{"name":"Redstone Repeater", "id":356, "data":0},
{"name":"Cookie", "id":357, "data":0},
{"name":"Map", "id":358, "data":0},
{"name":"Shears", "id":359, "data":0},
{"name":"Melon", "id":360, "data":0},
{"name":"Pumpkin Seeds", "id":361, "data":0},
{"name":"Melon Seeds", "id":362, "data":0},
{"name":"Raw Beef", "id":363, "data":0},
{"name":"Steak", "id":364, "data":0},
{"name":"Raw Chicken", "id":365, "data":0},
{"name":"Cooked Chicken", "id":366, "data":0},
{"name":"Rotten Flesh", "id":367, "data":0},
{"name":"Ender Pearl", "id":368, "data":0},
{"name":"Blaze Rod", "id":369, "data":0},
{"name":"Ghast Tear", "id":370, "data":0},
{"name":"Gold Nugget", "id":371, "data":0},
{"name":"Nether Wart", "id":372, "data":0},
{"name":"Potion", "id":373, "data":0},
{"name":"Glass Bottle", "id":374, "data":0},
{"name":"Spider Eye", "id":375, "data":0},
{"name":"Fermented Spider Eye", "id":376, "data":0},
{"name":"Blaze Powder", "id":377, "data":0},
{"name":"Magma Cream", "id":378, "data":0},
{"name":"Brewing Stand", "id":379, "data":0},
{"name":"Cauldron", "id":380, "data":0},
{"name":"Eye of Ender", "id":381, "data":0},
{"name":"Glistering Melon", "id":382, "data":0},
{"name":"Spawn Elder Guardian", "id":383, "data": 4},
{"name":"Spawn Wither Skeleton", "id":383, "data": 5},
{"name":"Spawn Stray", "id":383, "data": 6},
{"name":"Spawn Husk", "id":383, "data": 23},
{"name":"Spawn Zombie Villager", "id":383, "data": 27},
{"name":"Spawn Skeleton Horse", "id":383, "data": 28},
{"name":"Spawn Zombie Horse", "id":383, "data": 29},
{"name":"Spawn Donkey", "id":383, "data": 31},
{"name":"Spawn Mule", "id":383, "data": 32},
{"name":"Spawn Evoker", "id":383, "data": 34},
{"name":"Spawn Vex", "id":383, "data": 35},
{"name":"Spawn Vindicator", "id":383, "data": 36},
{"name":"Spawn Creeper", "id":383, "data": 50},
{"name":"Spawn Skeleton", "id":383, "data": 51},
{"name":"Spawn Spider", "id":383, "data": 52},
{"name":"Spawn Zombie", "id":383, "data": 54},
{"name":"Spawn Slime", "id":383, "data": 55},
{"name":"Spawn Ghast", "id":383, "data": 56},
{"name":"Spawn Pigman", "id":383, "data": 57},
{"name":"Spawn Enderman", "id":383, "data": 58},
{"name":"Spawn Cave Spider", "id":383, "data": 59},
{"name":"Spawn Silverfish", "id":383, "data": 60},
{"name":"Spawn Blaze", "id":383, "data": 61},
{"name":"Spawn Magma Cube", "id":383, "data": 62},
{"name":"Spawn Bat", "id":383, "data": 65},
{"name":"Spawn Witch", "id":383, "data": 66},
{"name":"Spawn Endermite", "id":383, "data": 67},
{"name":"Spawn Guardian", "id":383, "data": 68},
{"name":"Spawn Shulker", "id":383, "data": 69},
{"name":"Spawn Pig", "id":383, "data": 90},
{"name":"Spawn Sheep", "id":383, "data": 91},
{"name":"Spawn Cow", "id":383, "data": 92},
{"name":"Spawn Chicken", "id":383, "data": 93},
{"name":"Spawn Squid", "id":383, "data": 94},
{"name":"Spawn Wolf", "id":383, "data": 95},
{"name":"Spawn Mooshroom", "id":383, "data": 96},
{"name":"Spawn Ocelot", "id":383, "data": 98},
{"name":"Spawn Horse", "id":383, "data": 100},
{"name":"Spawn Rabbit", "id":383, "data": 101},
{"name":"Spawn Polar Bear", "id":383, "data": 102},
{"name":"Spawn Llama", "id":383, "data": 103},
{"name":"Spawn Villager", "id":383, "data": 120},
{"name":"Bottle o' Enchanting", "id":384, "data":0},
{"name":"Fire Charge", "id":385, "data":0},
{"name":"Book and Quill", "id":386, "data":0},
{"name":"Written Book", "id":387, "data":0},
{"name":"Emerald", "id":388, "data":0},
{"name":"Item Frame", "id":389, "data":0},
{"name":"Flower Pot", "id":390, "data":0},
{"name":"Carrot", "id":391, "data":0},
{"name":"Potato", "id":392, "data":0},
{"name":"Baked Potato", "id":393, "data":0},
{"name":"Poisonous Potato", "id":394, "data":0},
{"name":"Empty Map", "id":395, "data":0},
{"name":"Golden Carrot", "id":396, "data":0},
{"name":"Mob Head (Skeleton)", "id":397, "data":0},
{"name":"Mob Head (Wither Skeleton)", "id":397, "data": 1},
{"name":"Mob Head (Zombie)", "id":397, "data": 2},
{"name":"Mob Head (Human)", "id":397, "data": 3},
{"name":"Mob Head (Creeper)", "id":397, "data": 4},
{"name":"Mob Head (Dragon)", "id":397, "data": 5},
{"name":"Carrot on a Stick", "id":398, "data":0},
{"name":"Nether Star", "id":399, "data":0},
{"name":"Pumpkin Pie", "id":400, "data":0},
{"name":"Firework Rocket", "id":401, "data":0},
{"name":"Firework Star", "id":402, "data":0},
{"name":"Enchanted Book", "id":403, "data":0},
{"name":"Redstone Comparator", "id":404, "data":0},
{"name":"Nether Brick", "id":405, "data":0},
{"name":"Nether Quartz", "id":406, "data":0},
{"name":"Minecart with TNT", "id":407, "data":0},
{"name":"Minecart with Hopper", "id":408, "data":0},
{"name":"Prismarine Shard", "id":409, "data":0},
{"name":"Prismarine Crystals", "id":410, "data":0},
{"name":"Raw Rabbit", "id":411, "data":0},
{"name":"Cooked Rabbit", "id":412, "data":0},
{"name":"Rabbit Stew", "id":413, "data":0},
{"name":"Rabbit's Foot", "id":414, "data":0},
{"name":"Rabbit Hide", "id":415, "data":0},
{"name":"Armor Stand", "id":416, "data":0},
{"name":"Iron Horse Armor", "id":417, "data":0},
{"name":"Golden Horse Armor", "id":418, "data":0},
{"name":"Diamond Horse Armor", "id":419, "data":0},
{"name":"Lead", "id":420, "data":0},
{"name":"Name Tag", "id":421, "data":0},
{"name":"Minecart with Command Block", "id":422, "data":0},
{"name":"Raw Mutton", "id":423, "data":0},
{"name":"Cooked Mutton", "id":424, "data":0},
{"name":"Banner", "id":425, "data":0},
{"name":"Spruce Door", "id":427, "data":0},
{"name":"Birch Door", "id":428, "data":0},
{"name":"Jungle Door", "id":429, "data":0},
{"name":"Acacia Door", "id":430, "data":0},
{"name":"Dark Oak Door", "id":431, "data":0},
{"name":"Chorus Fruit", "id":432, "data":0},
{"name":"Popped Chorus Fruit", "id":433, "data":0},
{"name":"Beetroot", "id":434, "data":0},
{"name":"Beetroot Seeds", "id":435, "data":0},
{"name":"Beetroot Soup", "id":436, "data":0},
{"name":"Dragon's Breath", "id":437, "data":0},
{"name":"Splash Potion", "id":438, "data":0},
{"name":"Spectral Arrow", "id":439, "data":0},
{"name":"Tipped Arrow", "id":440, "data":0},
{"name":"Lingering Potion", "id":441, "data":0},
{"name":"Shield", "id":442, "data":0},
{"name":"Elytra", "id":443, "data":0},
{"name":"Spruce Boat", "id":444, "data":0},
{"name":"Birch Boat", "id":445, "data":0},
{"name":"Jungle Boat", "id":446, "data":0},
{"name":"Acacia Boat", "id":447, "data":0},
{"name":"Dark Oak Boat", "id":448, "data":0},
{"name":"Totem of Undying", "id":449, "data":0},
{"name":"Shulker Shell", "id":450, "data":0},
{"name":"Iron Nugget", "id":452, "data":0},
{"name":"13 Disc", "id":2256, "data":0},
{"name":"Cat Disc", "id":2257, "data":0},
{"name":"Blocks Disc", "id":2258, "data":0},
{"name":"Chirp Disc", "id":2259, "data":0},
{"name":"Far Disc", "id":2260, "data":0},
{"name":"Mall Disc", "id":2261, "data":0},
{"name":"Mellohi Disc", "id":2262, "data":0},
{"name":"Stal Disc", "id":2263, "data":0},
{"name":"Strad Disc", "id":2264, "data":0},
{"name":"Ward Disc", "id":2265, "data":0},
{"name":"11 Disc", "id":2266, "data":0},
{"name":"Wait Disc", "id":2267, "data":0}]
